#define cons_num	(vc_cons[currcons].d->vc_num)
#define sw		(vc_cons[currcons].d->vc_sw)
#define screenbuf	(vc_cons[currcons].d->vc_screenbuf)
#define screenbuf_size	(vc_cons[currcons].d->vc_screenbuf_size)
#define origin		(vc_cons[currcons].d->vc_origin)
#define scr_top		(vc_cons[currcons].d->vc_scr_top)
#define visible_origin  (vc_cons[currcons].d->vc_visible_origin)
#define scr_end		(vc_cons[currcons].d->vc_scr_end)
#define pos		(vc_cons[currcons].d->vc_pos)
#define top		(vc_cons[currcons].d->vc_top)
#define bottom		(vc_cons[currcons].d->vc_bottom)
#define x		(vc_cons[currcons].d->vc_x)
#define y		(vc_cons[currcons].d->vc_y)
#define vc_state	(vc_cons[currcons].d->vc_state)
#define npar		(vc_cons[currcons].d->vc_npar)
#define par		(vc_cons[currcons].d->vc_par)
#define priv4		(vc_cons[currcons].d->vc_priv4)
#define attr		(vc_cons[currcons].d->vc_attr)
#define saved_x		(vc_cons[currcons].d->vc_saved_x)
#define saved_y		(vc_cons[currcons].d->vc_saved_y)
#define translate	(vc_cons[currcons].d->vc_translate)
#define G0_charset	(vc_cons[currcons].d->vc_G0_charset)
#define G1_charset	(vc_cons[currcons].d->vc_G1_charset)
#define saved_G0	(vc_cons[currcons].d->vc_saved_G0)
#define saved_G1	(vc_cons[currcons].d->vc_saved_G1)
#define utf		(vc_cons[currcons].d->vc_utf)
#define utf_count	(vc_cons[currcons].d->vc_utf_count)
#define utf_char	(vc_cons[currcons].d->vc_utf_char)
#define video_erase_char (vc_cons[currcons].d->vc_video_erase_char)
#define disp_ctrl	(vc_cons[currcons].d->vc_disp_ctrl)
#define toggle_meta	(vc_cons[currcons].d->vc_toggle_meta)
#define decscnm		(vc_cons[currcons].d->vc_decscnm)
#define decom		(vc_cons[currcons].d->vc_decom)
#define decawm		(vc_cons[currcons].d->vc_decawm)
#define dectcem		(vc_cons[currcons].d->vc_dectcem)
#define irm		(vc_cons[currcons].d->vc_irm)
#define deccolm		(vc_cons[currcons].d->vc_deccolm)
#define need_wrap	(vc_cons[currcons].d->vc_need_wrap)
#define kmalloced	(vc_cons[currcons].d->vc_kmalloced)
#define report_mouse	(vc_cons[currcons].d->vc_report_mouse)
#define color		(vc_cons[currcons].d->vc_color)
#define s_color		(vc_cons[currcons].d->vc_s_color)
#define def_color	(vc_cons[currcons].d->vc_def_color)
#define foreground	(color & 0x0f)
#define background	(color & 0xf0)
#define charset		(vc_cons[currcons].d->vc_charset)
#define s_charset	(vc_cons[currcons].d->vc_s_charset)
#define	intensity	(vc_cons[currcons].d->vc_intensity)
#define	underline	(vc_cons[currcons].d->vc_underline)
#define	blink		(vc_cons[currcons].d->vc_blink)
#define	reverse		(vc_cons[currcons].d->vc_reverse)
#define	s_intensity	(vc_cons[currcons].d->vc_s_intensity)
#define	s_underline	(vc_cons[currcons].d->vc_s_underline)
#define	s_blink		(vc_cons[currcons].d->vc_s_blink)
#define	s_reverse	(vc_cons[currcons].d->vc_s_reverse)
#define	ulcolor		(vc_cons[currcons].d->vc_ulcolor)
#define	halfcolor	(vc_cons[currcons].d->vc_halfcolor)
#define tab_stop	(vc_cons[currcons].d->vc_tab_stop)
#define palette		(vc_cons[currcons].d->vc_palette)
#define bell_pitch	(vc_cons[currcons].d->vc_bell_pitch)
#define bell_duration	(vc_cons[currcons].d->vc_bell_duration)
#define cursor_type	(vc_cons[currcons].d->vc_cursor_type)
#define display_fg	(vc_cons[currcons].d->vc_display_fg)
#define complement_mask (vc_cons[currcons].d->vc_complement_mask)
#define s_complement_mask (vc_cons[currcons].d->vc_s_complement_mask)
#define hi_font_mask	(vc_cons[currcons].d->vc_hi_font_mask)

#define vcmode		(vt_cons[currcons]->vc_mode)

#define structsize	(sizeof(struct vc_data) + sizeof(struct vt_struct))

#ifdef CONFIG_VT_EXTENDED
#define decscl         (vc_cons[currcons].d->vc_decscl)
#define c8bit          (vc_cons[currcons].d->vc_c8bit)
#define d8bit          (vc_cons[currcons].d->vc_d8bit)
#define shift          (vc_cons[currcons].d->vc_shift)
#define priv1          (vc_cons[currcons].d->vc_priv1)
#define priv2          (vc_cons[currcons].d->vc_priv2)
#define priv3          (vc_cons[currcons].d->vc_priv3)
/* Private modes */
#define decckm         (vc_cons[currcons].d->vc_decckm)
#define decsclm                (vc_cons[currcons].d->vc_decsclm)
#define decarm         (vc_cons[currcons].d->vc_decarm)
#define decnrcm                (vc_cons[currcons].d->vc_decnrcm)
#define decnkm         (vc_cons[currcons].d->vc_decnkm)
/* ANSI / ISO mode flags */
#define kam            (vc_cons[currcons].d->vc_kam)
#define crm            (vc_cons[currcons].d->vc_crm)
#define lnm            (vc_cons[currcons].d->vc_lnm)
/* Charset mappings */
#define GL_charset     (vc_cons[currcons].d->vc_GL_charset)
#define GR_charset     (vc_cons[currcons].d->vc_GR_charset)
#define G2_charset     (vc_cons[currcons].d->vc_G2_charset)
#define G3_charset     (vc_cons[currcons].d->vc_G3_charset)
#define GS_charset     (vc_cons[currcons].d->vc_GS_charset)
#define saved_GL       (vc_cons[currcons].d->vc_saved_GL)
#define saved_GR       (vc_cons[currcons].d->vc_saved_GR)
#define saved_G2       (vc_cons[currcons].d->vc_saved_G2)
#define saved_G3       (vc_cons[currcons].d->vc_saved_G3)
#define saved_GS       (vc_cons[currcons].d->vc_saved_GS)
#endif /* def CONFIG_VT_EXTENDED */
