#!/bin/sh

rm -fv arch/m68k/hp300/hp300map.map
rm -rf drivers/acorn/char/defkeymap-l7200.c
rm -fv drivers/char/ec3104_keyb.c
rm -fv drivers/tc/lk201.c
rm -fv drivers/tc/lk201-remap.c
rm -rf drivers/tc/lk201-map.map
rm -fv include/asm-m68k/adb_mouse.h
rm -fv include/asm-m68k/atari_joystick.h
rm -fv include/asm-m68k/mac_mouse.h
rm -fv include/asm-m68k/atarikb.h
rm -fv include/linux/console_struct.h
