.TH ffset 1 "March 8, 2009" ffset
.SH NAME
ffset \- set force-feedback device parameters
.SH SYNOPSIS
.B ffset
.RI "<" device "> [\fB\-g\fP <" gain ">] [\fB\-a\fP <" "autocenter strength" ">]"
.SH "DESCRIPTION"
ffset sets the gain and autocenter strength of a force-feedback
device.
.SH OPTIONS
.TP
.RI "<" device ">"
The device to configure.
.TP
.BR \-g " <\fIgain\fP>"
The gain (0-100).
.TP
.BR \-a " <\fIautocenter strength\fP>"
The autocenter strength (0-100).
.SH SEE ALSO
\fBffcfstress\fP(1), \fBffmvforce\fP(1), \fBfftest\fP(1), \fBjscal\fP(1), \fBjstest\fP(1).
.SH AUTHOR
.B ffset
was written by Johann Deneux.
.PP
This manual page was written by Stephen Kitt <steve@sk2.org>, for the
Debian GNU/Linux system (but may be used by others).
It was last modified for
.B ffmvforce
dated May 30, 2001.
