.TH fftest 1 "March 8, 2009" fftest
.SH NAME
fftest \- tests force-feedback devices.
.SH SYNOPSIS
.B fftest
.RI "<" device ">"
.SH "DESCRIPTION"
fftest provides a variety of tests which can be applied to
force-feedback devices.
.B Beware, the tests may damage your device!
.SH OPTIONS
.TP
.RI "<" device ">"
The device to test.
.SH SEE ALSO
\fBffcfstress\fP(1), \fBffmvforce\fP(1), \fBjstest\fP(1).
.SH AUTHOR
.B fftest
was written by Johann Deneux.
.PP
This manual page was written by Stephen Kitt <steve@sk2.org>, for the Debian
GNU/Linux system (but may be used by others).
It was last modified for
.B fftest
dated October 19, 2004.
